module.exports = {
  FETCH_PICTURE_REQUEST: "FETCH_PICTURE_REQUEST",
  FETCH_PICTURE_SUCCESS: "FETCH_PICTURE_SUCCESS",
  FETCH_PICTURE_FAILURE: "FETCH_PICTURE_FAILURE",
  FETCH_MOVIES_REQUEST: "FETCH_MOVIES_REQUEST",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_FAILURE: "FETCH_MOVIES_FAILURE",
  FETCH_SINGLE_MOVIE_REQUEST: "FETCH_SINGLE_MOVIE_REQUEST",
  FETCH_SINGLE_MOVIE_SUCCESS: "FETCH_SINGLE_MOVIE_SUCCESS",
  FETCH_SINGLE_MOVIE_FAILURE: "FETCH_SINGLE_MOVIE_FAILURE",
};
